# Generated by Django 4.1.3 on 2024-03-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sent_date',
        ),
    ]
