# Generated by Django 4.1.3 on 2024-03-14 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sent_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
