# Generated by Django 4.1.3 on 2024-03-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_appointment_accepted_appointment_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-sent_date']},
        ),
    ]
