# Generated by Django 4.1.3 on 2024-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_delete_doctorform'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
