# Generated by Django 4.1.3 on 2024-03-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_doctorform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctorform',
        ),
    ]
