# Generated by Django 4.1.3 on 2024-03-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_doctorsignup_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsignup',
            name='password',
        ),
    ]
