# Generated by Django 4.1.3 on 2024-03-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_doctorsignup_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctorsignup',
        ),
    ]
