# Generated by Django 4.1.3 on 2024-03-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_doctorsignup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctorsignup',
            new_name='Hospitalsignup',
        ),
    ]
