# Generated by Django 4.1.3 on 2024-03-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_rename_doctorsignup_hospitalsignup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitalsignup',
            new_name='Hospital',
        ),
    ]
