# Generated by Django 5.0.2 on 2024-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sent_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
