# Generated by Django 5.0.2 on 2024-03-28 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_appointment_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
