# Generated by Django 5.0.2 on 2024-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['sent_date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.CharField(choices=[('naroda', 'NARODA'), ('satellite', 'SATELLITE'), ('ranip', 'RANIP'), ('maninagar', 'MANINAGAR')], default='naroda', max_length=50),
        ),
    ]
