# Generated by Django 5.0.2 on 2024-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_appointment_options_appointment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
