# Generated by Django 5.0.2 on 2024-03-29 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_appointment_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejected_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
