# Generated by Django 5.0.2 on 2024-04-01 13:47

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_appointment_rejected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sent_date',
            field=models.DateTimeField(),
        ),
    ]
